spring:
  application:
    name: securecapita
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false
